#!/usr/bin/env python3

"""
Based on: Arisoy, B., Betz, F., Stauch, G., Klein, D., Dech, S., & Ullmann, T. (2025). stac2cube (Version 1.3.0).
          Zenodo. https://doi.org/10.5281/zenodo.18459201
Author: Mohajane Meriame
Adapted by: Victoria León
Project: SR4LC

Description:
Run SEN2SRLite Full Spectral super-resolution on a Sentinel-2 data cube
generated by STAC2Cube.

This workflow uses the required Sentinel-2 bands for the Full Spectral model:
- 10 m bands: blue, green, red, nir
- 20 m bands: nir08, rededge1, rededge2, rededge3, swir16, swir22

Use this workflow only when 20 m bands need to be super-resolved.
Even if only one 20 m band is needed, all required bands must be present
in the input cube.

Outputs:
- Super-resolved NetCDF cube
- GeoTIFF/COGs for QGIS validation
- Text report/log
"""


# =============================================================================
# 0. PYTHON PATH SETUP
# =============================================================================

import sys
from pathlib import Path

project_root = Path(__file__).resolve().parents[3]
sys.path.append(str(project_root))


# =============================================================================
# 1. IMPORTS
# =============================================================================

import io
import mlstac

from contextlib import redirect_stdout, redirect_stderr
from dataclasses import dataclass
from typing import TextIO, cast

import xarray as xr

import utils.super_resolution_Lite as sr_mod

from utils.export_cfg import export_to_cogs
from utils.common import lazy_data_size
from utils.naming import build_run_name
from utils.paths import create_output_dir


# =============================================================================
# 2. CONFIGURATION CLASS
# =============================================================================

@dataclass
class SuperResolutionLiteFullConfig:
    """
    Configuration for SEN2SRLite Full Spectral super-resolution.
    """

    input_path: str

    output_path: str | None = None
    export_cogs_dir: str | None = None
    report_path: str | None = None

    model_type: str = "full_spectral"

    bands: tuple[str, ...] = (
        "blue",
        "green",
        "red",
        "nir",
        "nir08",
        "rededge1",
        "rededge2",
        "rededge3",
        "swir16",
        "swir22",
    )


# =============================================================================
# 3. LOAD DATAARRAY / HELPERS
# =============================================================================

class Tee(io.TextIOBase):
    """
    Write terminal output also into a report file.
    """

    def __init__(self, *streams: TextIO):
        super().__init__()
        self.streams = streams

    def write(self, data: str) -> int:
        for stream in self.streams:
            stream.write(data)
            stream.flush()

        return len(data)

    def flush(self) -> None:
        for stream in self.streams:
            stream.flush()


def ensure_parent(path_str: str | None) -> Path | None:
    """
    Create parent directory for a file path.
    """

    if path_str is None:
        return None

    path = Path(path_str)
    path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    return path


def infer_output_path(
    input_path: str,
    output_path: str | None
) -> str:
    """
    Infer output path if none is provided.
    """

    if output_path:
        return output_path

    input_file = Path(input_path)
    suffix = input_file.suffix or ".nc"

    return str(
        input_file.with_name(
            f"{input_file.stem}_sr{suffix}"
        )
    )


def patch_mlstac_load():
    """
    Patch mlstac.load to redirect Full Spectral model path.
    """

    original_load = mlstac.load

    model_root = (
        "/teamspace/studios/this_studio/"
        "STAC2Cube/4_SuperResolution/"
        "SEN2SR_Lite/model/"
        "SEN2SRLite"
    )

    def patched_load(source, *args, **kwargs):

        source_str = str(source)

        if source_str == "model/SEN2SRLite":

            source = model_root

            print(
                "\nRedirecting Full Spectral model:"
                f"\n  from: model/SEN2SRLite"
                f"\n  to:   {source}"
            )

        return original_load(
            source,
            *args,
            **kwargs
        )

    mlstac.load = patched_load

    return original_load


def load_output_cube(
    output_path: str
) -> xr.Dataset:
    """
    Load super-resolved NetCDF output.
    """

    with xr.open_dataset(output_path) as ds:
        ds_loaded = ds.load()

    return ds_loaded


# =============================================================================
# 4. RUN WORKFLOW
# =============================================================================

def run_super_resolution(
    config: SuperResolutionLiteFullConfig
) -> xr.Dataset:
    """
    Run SEN2SRLite Full Spectral super-resolution.
    """

    input_path = str(
        Path(config.input_path).resolve()
    )

    output_path_obj = ensure_parent(
        config.output_path
    )

    output_path = infer_output_path(
        input_path=input_path,
        output_path=(
            str(output_path_obj)
            if output_path_obj
            else None
        ),
    )

    if not Path(input_path).exists():
        raise FileNotFoundError(
            f"Input cube not found: {input_path}"
        )

    if config.model_type != "full_spectral":
        raise ValueError(
            "This workflow only supports model_type='full_spectral'."
        )

    original_load = patch_mlstac_load()

    try:
        sr_mod.super_resolve_cube(
            input_path=input_path,
            output_path=output_path,
            model_type=config.model_type,
        )

    finally:
        mlstac.load = original_load

    print("\nSuper-resolution finished successfully.")
    print(f"\nInput cube: {input_path}")
    print(f"Model type: {config.model_type}")
    print(f"Output NetCDF: {output_path}")

    ds_sr = load_output_cube(output_path)

    if config.export_cogs_dir:

        Path(config.export_cogs_dir).mkdir(
            parents=True,
            exist_ok=True
        )

        export_to_cogs(
            ds_sr,
            config.export_cogs_dir
        )

        print(
            f"\nExported GeoTIFF/COGs to: "
            f"{config.export_cogs_dir}"
        )

    return ds_sr


# =============================================================================
# 5. PRINT SUMMARY
# =============================================================================

def print_summary(
    ds_sr: xr.Dataset
) -> None:
    """
    Print summary of super-resolved output cube.
    """

    print("\nSuper-resolved cube summary:")

    print(f"\nVariables: {list(ds_sr.data_vars)}")

    print(f"\nDimensions: {dict(ds_sr.sizes)}")

    print(f"\nEstimated size: {lazy_data_size(ds_sr)}")

    if "time" in ds_sr.coords:

        print("\nAvailable dates:")

        for value in ds_sr.time.values:
            print(f"  {value}")


# =============================================================================
# 6. MAIN WORKFLOW
# =============================================================================

def main() -> None:
    """
    Run SEN2SRLite Full Spectral workflow.
    """

    print("ENTERED MAIN")

    # =========================================================
    # Base Lightning storage directory
    # =========================================================

    base_dir = (
        "/teamspace/lightning_storage/"
        "pKq003_SR4LC_Data"
    )

    print("BASE DIR OK")

    # =========================================================
    # Input cube
    # =========================================================

    # IMPORTANT:
    # This cube must contain all 10 Full Spectral bands.
    input_cube = (
        "/teamspace/lightning_storage/pKq003_SR4LC_Data/outputs/comparison_tests/Coregistration/Coreg_FS_Area2_20260521_1358/Coreg_FS_Area2_20260521_1358.nc"
    )

    print("INPUT CUBE OK")
    print(input_cube)

    # =========================================================
    # Automatic naming logic
    # =========================================================

    input_name = Path(input_cube).stem
 
    # Remove previous workflow prefixes
    input_name = (
        input_name
        .replace("LR_Cube_", "")
        .replace("CloudMask_RGBN_", "")
        .replace("CloudMask_FS_", "")
        .replace("Coreg_RGBN_", "")
        .replace("Coreg_FS_", "")
    )

    run_name = build_run_name(
        prefix="SR_Lite_Full",
        polygon_name=input_name,
        location_code=None,
    )

    print("RUN NAME OK")
    print(run_name)

    # =========================================================
    # Create standardized output directory
    # =========================================================

    output_dir = create_output_dir(
        base_dir=base_dir,
        workflow_step="comparison_tests/SuperResolution/SEN2SRLite/FullSpectral",
        run_name=run_name,
    )

    print("OUTPUT DIR OK")
    print(output_dir)

    # =========================================================
    # Super-resolution configuration
    # =========================================================

    config = SuperResolutionLiteFullConfig(

        # Input NetCDF cube from STAC2Cube / cloud mask / co-registration
        input_path=input_cube,

        # Super-resolved NetCDF output
        output_path=str(
            output_dir / f"{run_name}.nc"
        ),

        # GeoTIFF/COG export directory
        export_cogs_dir=str(
            output_dir / "cogs"
        ),

        # Report/log file
        report_path=str(
            output_dir / f"{run_name}_report.txt"
        ),

        # SEN2SRLite Full Spectral model
        model_type="full_spectral",

        # Required Full Spectral bands
        bands=(
            "blue",
            "green",
            "red",
            "nir",
            "nir08",
            "rededge1",
            "rededge2",
            "rededge3",
            "swir16",
            "swir22",
        ),
    )

    print("CONFIG OK")
    print(config)

    # =========================================================
    # Run workflow with report
    # =========================================================

    report_path = ensure_parent(
        config.report_path
    )

    if report_path:

        with open(
            report_path,
            "w",
            encoding="utf-8"
        ) as report_file:

            tee = Tee(
                sys.__stdout__ or sys.stdout,
                report_file
            )

            with redirect_stdout(report_file), redirect_stderr(report_file):

                print("Starting SEN2SRLite Full Spectral super-resolution...")
                print(f"\nProject root: {project_root}")
                print(f"Report path: {report_path}")

                ds_sr = run_super_resolution(config)

                print_summary(ds_sr)

                print("\nReport saved successfully.")

    else:

        ds_sr = run_super_resolution(config)

        print_summary(ds_sr)

    print("REPORT PATH OK")
    print(report_path)

# =============================================================================
# 7. SCRIPT ENTRY POINT
# =============================================================================

if __name__ == "__main__":

    print("\nSCRIPT STARTED\n")

    try:

        main()

    except Exception as error:

        print("\nERROR DETECTED:\n")
        print(error)

        raise