#!/usr/bin/env python3

"""
Based on: Arisoy, B., Betz, F., Stauch, G., Klein, D., Dech, S., & Ullmann, T. (2025). stac2cube (Version 1.3.0). 
          Zenodo. https://doi.org/10.5281/zenodo.18459201
Author: Mohajane Meriame
Adapted by: Victoria León
Project: SR4LC

Description:
Run SEN2SRLite RGBN super-resolution on a Sentinel-2 data cube
generated by STAC2Cube.

This workflow uses only Sentinel-2 10 m bands:
blue, green, red, nir.

Outputs:
- Super-resolved NetCDF cube
- GeoTIFF/COGs for QGIS validation
- Text report/log
"""

# =============================================================================
# 0. PYTHON PATH SETUP
# =============================================================================

import sys
from pathlib import Path

# Add project root to Python path
project_root = Path(__file__).resolve().parents[3]

sys.path.append(str(project_root))


# =============================================================================
# 1. IMPORTS
# =============================================================================

import io
import mlstac

from contextlib import redirect_stdout, redirect_stderr
from dataclasses import dataclass
from typing import TextIO
import json

import xarray as xr

# Local STAC2Cube super-resolution module
import utils.super_resolution_Lite as sr_mod

# Helper functions
from utils.export_cfg import export_to_cogs
from utils.common import lazy_data_size
from utils.naming import build_run_name
from utils.paths import create_output_dir


# =============================================================================
# 2. CONFIGURATION CLASS
# =============================================================================

@dataclass
class SuperResolutionLiteRGBNConfig:
    """
    Configuration for SEN2SRLite RGBN super-resolution.
    """

    input_path: str

    output_path: str | None = None
    export_cogs_dir: str | None = None
    report_path: str | None = None

    model_type: str = "rgbn"

    bands: tuple[str, ...] = (
        "blue",
        "green",
        "red",
        "nir",
    )

    stac2cube_root: str | None = None


# =============================================================================
# 3. LOAD DATAARRAY / HELPERS
# =============================================================================

class Tee:
    """
    Write terminal output also into a report file.
    """

    def __init__(self, *streams: TextIO):
        self.streams = streams

    def write(self, data: str) -> int:
        for stream in self.streams:
            stream.write(data)
            stream.flush()

        return len(data)

    def flush(self) -> None:
        for stream in self.streams:
            stream.flush()


def ensure_parent(path_str: str | None) -> Path | None:
    """
    Create parent directory for a file path.
    """

    if path_str is None:
        return None

    path = Path(path_str)
    path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    return path


def infer_output_path(
    input_path: str,
    output_path: str | None
) -> str:
    """
    Infer output path if none is provided.
    """

    if output_path:
        return output_path

    input_file = Path(input_path)
    suffix = input_file.suffix or ".nc"

    return str(
        input_file.with_name(
            f"{input_file.stem}_sr{suffix}"
        )
    )


def is_stac_json(json_path: Path) -> bool:
    """
    Check if a JSON file looks like a valid STAC JSON.
    """

    try:
        with json_path.open(
            "r",
            encoding="utf-8"
        ) as file:
            obj = json.load(file)

    except Exception:
        return False

    if not isinstance(obj, dict):
        return False

    if "stac_version" not in obj:
        return False

    stac_type = obj.get("type")

    if stac_type in {
        "Feature",
        "Collection",
        "Catalog",
    }:
        return True

    if "assets" in obj or "links" in obj:
        return True

    return False


def resolve_rgbn_model_source(
    stac2cube_root: Path
) -> str:
    """
    Find local SEN2SRLite RGBN model STAC JSON.
    """

    candidate_dirs = [
        stac2cube_root / "interactive" / "model" / "SEN2SRLite_RGBN",
        stac2cube_root / "interactive" / "model" / "SEN2SRLite-RGBN",
        stac2cube_root / "model" / "SEN2SRLite_RGBN",
        stac2cube_root / "model" / "SEN2SRLite-RGBN",
    ]

    preferred_names = [
        "mlm.json",
        "item.json",
        "catalog.json",
        "collection.json",
        "model.json",
    ]

    for model_dir in candidate_dirs:

        if not model_dir.is_dir():
            continue

        print(f"\nSearching model directory: {model_dir}")

        json_files = sorted(
            model_dir.rglob("*.json")
        )

        for name in preferred_names:
            for json_file in json_files:

                if (
                    json_file.name.lower() == name
                    and is_stac_json(json_file)
                ):
                    print(f"Using model STAC JSON: {json_file}")
                    return str(json_file)

        for json_file in json_files:

            if is_stac_json(json_file):
                print(f"Using model STAC JSON: {json_file}")
                return str(json_file)

        raise FileNotFoundError(
            f"No valid STAC JSON found in model directory: {model_dir}"
        )

    searched = "\n".join(
        str(path)
        for path in candidate_dirs
    )

    raise FileNotFoundError(
        "Could not locate SEN2SRLite RGBN model directory. "
        "Searched:\n"
        + searched
    )


def patch_mlstac_load():
    """
    Patch mlstac.load to redirect RGBN model path.
    """

    original_load = mlstac.load

    model_root = (
        "/teamspace/studios/this_studio/"
        "STAC2Cube/4_SuperResolution/"
        "SEN2SR_Lite/model/"
        "SEN2SRLite_RGBN"
    )

    def patched_load(source, *args, **kwargs):

        source_str = str(source)

        if source_str == "model/SEN2SRLite-RGBN":

            source = model_root

            print(
                "\nRedirecting RGBN model:"
                f"\n  from: model/SEN2SRLite-RGBN"
                f"\n  to:   {source}"
            )

        return original_load(
            source,
            *args,
            **kwargs
        )

    mlstac.load = patched_load

    return original_load


def load_output_cube(
    output_path: str
) -> xr.Dataset:
    """
    Load super-resolved NetCDF output.
    """

    with xr.open_dataset(output_path) as ds:
        ds_loaded = ds.load()

    return ds_loaded


# =============================================================================
# 4. RUN WORKFLOW
# =============================================================================

def run_super_resolution(
    config: SuperResolutionLiteRGBNConfig
) -> xr.Dataset:
    """
    Run SEN2SRLite RGBN super-resolution.
    """

    input_path = str(
        Path(config.input_path).resolve()
    )

    output_path_obj = ensure_parent(
        config.output_path
    )

    output_path = infer_output_path(
        input_path=input_path,
        output_path=(
            str(output_path_obj)
            if output_path_obj
            else None
        ),
    )

    if not Path(input_path).exists():
        raise FileNotFoundError(
            f"Input cube not found: {input_path}"
        )

    if config.model_type != "rgbn":
        raise ValueError(
            "This workflow only supports model_type='rgbn'."
        )

    original_load = patch_mlstac_load()

    try:
        sr_mod.super_resolve_cube(
            input_path=input_path,
            output_path=output_path,
            model_type=config.model_type,
        )
    
    finally:
        mlstac.load = original_load

    print("\nSuper-resolution finished successfully.")
    print(f"\nInput cube: {input_path}")
    print(f"Model type: {config.model_type}")
    print(f"Output NetCDF: {output_path}")

    ds_sr = load_output_cube(output_path)

    if config.export_cogs_dir:

        Path(config.export_cogs_dir).mkdir(
            parents=True,
            exist_ok=True
        )

        export_to_cogs(
            ds_sr,
            config.export_cogs_dir
        )

        print(
            f"\nExported GeoTIFF/COGs to: "
            f"{config.export_cogs_dir}"
        )

    return ds_sr


# =============================================================================
# 5. PRINT SUMMARY
# =============================================================================

def print_summary(
    ds_sr: xr.Dataset
) -> None:
    """
    Print summary of super-resolved output cube.
    """

    print("\nSuper-resolved cube summary:")

    print(f"\nVariables: {list(ds_sr.data_vars)}")

    print(f"\nDimensions: {dict(ds_sr.sizes)}")

    print(f"\nEstimated size: {lazy_data_size(ds_sr)}")

    if "time" in ds_sr.coords:

        print("\nAvailable dates:")

        for value in ds_sr.time.values:
            print(f"  {value}")


# =============================================================================
# 6. MAIN WORKFLOW
# =============================================================================

def main() -> None:
    """
    Run SEN2SRLite RGBN workflow.
    """

    print("ENTERED MAIN")

    # =========================================================
    # Base Lightning storage directory
    # =========================================================

    base_dir = (
        "/teamspace/lightning_storage/"
        "pKq003_SR4LC_Data"
    )

    print("BASE DIR OK")

    # =========================================================
    # Input cube
    # =========================================================

    input_cube = (
        "/teamspace/lightning_storage/pKq003_SR4LC_Data/outputs/comparison_tests/Coregistration/Coreg_RGBN_Area2_20260521_1437/Coreg_RGBN_Area2_20260521_1437.nc"
    )

    print("INPUT CUBE OK")
    print(input_cube)

    # =========================================================
    # Automatic naming logic
    # =========================================================

    input_name = Path(input_cube).stem

    # Remove previous workflow prefixes
    input_name = (
        input_name
        .replace("LR_Cube_", "")
        .replace("CloudMask_RGBN_", "")
        .replace("CloudMask_FS_", "")
        .replace("Coreg_RGBN_", "")
        .replace("Coreg_FS_", "")
    )

    run_name = build_run_name(
        prefix="SR_Lite_RGBN",
        polygon_name=input_name,
        location_code=None,
    )

    print("RUN NAME OK")
    print(run_name)

    # =========================================================
    # Create standardized output directory
    # =========================================================

    output_dir = create_output_dir(
        base_dir=base_dir,
        workflow_step="comparison_tests/SuperResolution/SEN2SRLite/RGBN",
        run_name=run_name,
    )

    print("OUTPUT DIR OK")
    print(output_dir)

    # =========================================================
    # Super-resolution configuration
    # =========================================================

    config = SuperResolutionLiteRGBNConfig(

        # Input NetCDF cube from STAC2Cube / cloud mask / co-registration
        input_path=input_cube,

        # Super-resolved NetCDF output
        output_path=str(
            output_dir / f"{run_name}.nc"
        ),

        # GeoTIFF/COG export directory
        export_cogs_dir=str(
            output_dir / "cogs"
        ),

        # Report/log file
        report_path=str(
            output_dir / f"{run_name}_report.txt"
        ),

        # SEN2SRLite RGBN model
        model_type="rgbn",

        # Required RGBN bands
        bands=(
            "blue",
            "green",
            "red",
            "nir",
        ),

        # Local stac2cube source folder
        stac2cube_root=str(
            project_root / "stac2cube-main"
        ),
    )

    print("CONFIG OK")
    print(config)

    # =========================================================
    # Run workflow with report
    # =========================================================

    report_path = ensure_parent(
        config.report_path
    )

    if report_path:

        with open(
            report_path,
            "w",
            encoding="utf-8"
        ) as report_file:

            tee = Tee(
                sys.__stdout__ or sys.stdout,
                report_file
            )

            with redirect_stdout(report_file), redirect_stderr(report_file):

                print("Starting SEN2SRLite RGBN super-resolution...")
                print(f"\nProject root: {project_root}")
                print(f"Report path: {report_path}")

                ds_sr = run_super_resolution(config)

                print_summary(ds_sr)

                print("\nReport saved successfully.")

    else:

        ds_sr = run_super_resolution(config)

        print_summary(ds_sr)

    print("REPORT PATH OK")
    print(report_path)


# =============================================================================
# 7. SCRIPT ENTRY POINT
# =============================================================================

if __name__ == "__main__":

    print("\nSCRIPT STARTED\n")

    try:

        main()

    except Exception as error:

        print("\nERROR DETECTED:\n")
        print(error)

        raise
